create table Comment (id integer not null auto_increment, content varchar(255) not null, date datetime(6) not null, author_id integer not null, lessonNote_id integer not null, primary key (id)) engine=InnoDB;
create table LessonNote (id integer not null auto_increment, content varchar(2000) not null, date datetime(6) not null, lastContentUpdate datetime(6) not null, author_id integer not null, topic_id integer not null, primary key (id)) engine=InnoDB;
create table Notebook (id integer not null auto_increment, activeOrder integer not null, archiveOrder integer not null, dateArchived datetime(6), dateCreated datetime(6) not null, isActive bit not null, name VARCHAR(125) COLLATE latin1_general_cs not null, uiPreference varchar(255) not null, studio_id integer not null, primary key (id)) engine=InnoDB;
create table NotebookUserRole (id integer not null auto_increment, role varchar(255) not null, notebook_id integer not null, user_id integer not null, primary key (id)) engine=InnoDB;
create table Studio (id integer not null auto_increment, name varchar(255) not null, uiPreference varchar(255), owner_id integer not null, primary key (id)) engine=InnoDB;
create table Tag (id integer not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table Tag_UiPreference (Tag_id integer not null, uiPreference_id bigint not null, primary key (Tag_id, uiPreference_id)) engine=InnoDB;
create table Topic (id integer not null auto_increment, activeOrder integer not null, dateArchived datetime(6), dateCreated datetime(6) not null, graphic varchar(255), information varchar(255), name varchar(255) not null, shortname varchar(255) not null, topicState varchar(255) not null, uiPreference varchar(255), lastLessonNote_id integer, notebook_id integer not null, primary key (id)) engine=InnoDB;
create table Topic_Tag (Topic_id integer not null, tag_id integer not null, primary key (Topic_id, tag_id)) engine=InnoDB;
create table TopicTag (id integer not null auto_increment, tag_id integer not null, topic_id integer not null, primary key (id)) engine=InnoDB;
create table UiPreference (id bigint not null, mapkey varchar(255) not null, value varchar(255) not null, primary key (id)) engine=InnoDB;
create table User (id integer not null auto_increment, email varchar(255) not null, name varchar(255) not null, uiPreference varchar(255), primary key (id)) engine=InnoDB;
create table UserIdentity (id integer not null auto_increment, password binary(32) not null, privileges varchar(255), salt varchar(255), user_id integer not null, primary key (id)) engine=InnoDB;
alter table Notebook add constraint UniqueNotebookName unique (name, studio_id);
alter table NotebookUserRole add constraint UniqueUserInNotebook unique (notebook_id, user_id);
alter table Tag_UiPreference add constraint UniqueTagUi unique (uiPreference_id);
alter table Topic add constraint UniqueTopicName unique (name, notebook_id);
alter table User add constraint UniqueUserName unique (name);
alter table User add constraint UniqueUserEmail unique (email);
alter table Comment add constraint CommentAuthorFkConstraint foreign key (author_id) references User (id);
alter table Comment add constraint CommentLessonNoteFkConstraint foreign key (lessonNote_id) references LessonNote (id);
alter table LessonNote add constraint LessonNoteAuthorFkConstraint foreign key (author_id) references User (id);
alter table LessonNote add constraint LessonNoteTopicFkConstraint foreign key (topic_id) references Topic (id);
alter table Notebook add constraint NotebookStudioFkConstraint foreign key (studio_id) references Studio (id);
alter table NotebookUserRole add constraint NotebookUserRoleNotebookFkConstraint foreign key (notebook_id) references Notebook (id);
alter table NotebookUserRole add constraint NotebookUserRoleUserFkConstraint foreign key (user_id) references User (id);
alter table Studio add constraint StudioOwnerFKConstraint foreign key (owner_id) references User (id);
alter table Tag_UiPreference add constraint TagUiPreferenceUiPreferenceFkConstraint foreign key (uiPreference_id) references UiPreference (id);
alter table Tag_UiPreference add constraint TagUiPreferenceTagFkConstraint foreign key (Tag_id) references Tag (id);
alter table Topic add constraint TopicLastLessonNoteFkConstraint foreign key (lastLessonNote_id) references LessonNote (id);
alter table Topic add constraint TopicNotebookFkConstraint foreign key (notebook_id) references Notebook (id);
alter table Topic_Tag add constraint TopicTag2TagFkConstraint foreign key (tag_id) references Tag (id);
alter table Topic_Tag add constraint TopicTag2TopicFkConstraint foreign key (Topic_id) references Topic (id);
alter table TopicTag add constraint TopicTagTagFkConstraint foreign key (tag_id) references Tag (id);
alter table TopicTag add constraint TopicTagTopicFkConstraint foreign key (topic_id) references Topic (id);
alter table UserIdentity add constraint UserIdentityUserFkConstraint foreign key (user_id) references User (id);
